language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nunogoncalosilva/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nunogoncalosilva/react-test npm test

after_success:
  - docker build -t nunogoncalosilva/multi-client ./client
  - docker build -t nunogoncalosilva/multi-nginx ./nginx
  - docker build -t nunogoncalosilva/multi-server ./server
  - docker build -t nunogoncalosilva/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nunogoncalosilva/multi-client
  - docker push nunogoncalosilva/multi-nginx
  - docker push nunogoncalosilva/multi-server
  - docker push nunogoncalosilva/multi-worker
